# Generated by Django 4.2 on 2023-05-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom1App', '0005_businessaccinfo_user_sellerinfo_user_productspec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productspec',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
        migrations.DeleteModel(
            name='ProductSpec',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
